ParkGolfOne/pirogramming_final_project

server/config/settings.py

[fix] after login redirect

---

server/config/settings.py

[fix] login 이후 refirect 찐

---

server/apps/communitys/views.py

[fix] 게시판 수정페이지 오류, 좋아요, 스크랩 오류 수정

---

server/apps/communitys/forms.py
server/apps/communitys/models.py
server/config/settings.py
server/templates/communitys/posts/post_create.html
server/templates/communitys/posts/post_detail.html
server/templates/communitys/posts/post_update.html

tiny로 게시물 html형식 글 작석 가능 html형식 글을 보이기 위해서 장고 템플릿 {{html필드인 변수 | safe}} 로 해야합니다!

[feat] 게시물 content-html형식으로 작성 구현

---

server/apps/score/urls.py
server/apps/score/views.py
server/static/score/css/score_detail.css
server/static/score/js/chart.js
server/templates/score/score_detail.html
server/templates/score/score_history.html

[fix] 그래프 초기 코드 작성

---

server/apps/users/models.py
server/apps/users/urls.py
server/apps/users/views.py
server/static/users/js/signup.js
server/static/users/js/update.js
server/templates/base.html
server/templates/users/users_main.html
server/templates/users/users_signup.html
server/templates/users/users_update.html

유저 + region 문제 해결 끝~
기존 dev branch에서 users.region이 삭제가 안되어서... 삽질하느라 오래 걸림ㅠ
+ js 파일 구조도 기존에 올려준 방식대로 users 이름의 폴더 만들어서 넣었음
+ js import는 해당 파일을 사용하는 코드에서 import 함

[fix] 회원 정보 수정 페이지도 폼+input 형식으로 수정

---

server/apps/communitys/views.py
server/apps/score/forms.py
server/apps/score/models.py
server/apps/score/views.py
server/static/score/css/score_detail.css
server/static/score/js/chart.js
server/templates/score/score_create.html
server/templates/score/score_detail.html
server/templates/score/score_history.html

Feature/score/yang 스코어 차트, 입력 방식 변경

---

server/config/settings.py

[feat] DB 서버 연결

---

server/apps/score/views.py
server/static/score/js/picture.js
server/templates/score/score_update.html

[fix] 이미지 추출 버튼 중복입력 방지 & 진행상황 표시

---

server/apps/search/urls.py
server/apps/search/views.py
server/apps/users/views.py
server/static/search/js/search_friend.js
server/static/users/js/add_friend.js
server/static/users/js/delete_friend.js
server/templates/search/search_friend.html
server/templates/users/add_friend.html
server/templates/users/friend_list.html

- 친구 추가/삭제 목록을 url reload 없이 진행
- 자동완성에서 마우스 커서가 input에 있으면 버튼 한번 클릭으로 안된다고 한거 해결 못함... (아까 다 한줄ㅠ)
[추가로]
- 자동완성 기능은 search app에 그냥 search는 user로 넣었는데 그 경계가 애매하다.. 
- @yanghyeonee 현이 search app 어떻게 진행했는지 내일 공유 부탁!

[fix] 친구목록 ajax로 수정

---

server/templates/users/users_signup.html

[fix] user 회원가입에 빠진 id 추가

---

server/apps/users/forms.py
server/apps/users/models.py
server/apps/users/views.py
server/static/board/js/board_search.js
server/static/search/js/search_friend.js
server/static/users/js/signup.js
server/templates/users/users_signup.html

[feat] users에 도로명 주소 추가

---

server/apps/communitys/models.py
server/apps/communitys/views.py
server/static/posts/js/search_post.js
server/templates/communitys/posts/post_detail.html
server/templates/communitys/posts/post_list.html

[fix] 게시판 조회수, 조회수 정렬 기능 추가

---

server/static/locations/javascript/location_script.js
server/static/locations/javascript/myposition_script.js
server/templates/locations/location_myplace.html

[fix] 현재 사용자 위치 지도 표시

---

server/apps/users/backends.py
server/apps/users/forms.py
server/apps/users/models.py
server/apps/users/views.py
server/static/board/css/board_list.css
server/static/main/css/style.css
server/static/search/js/search_friend.js
server/static/users/css/add_friend.css
server/static/users/js/add_friend.js
server/static/users/js/signup.js
server/templates/users/add_friend.html
server/templates/users/users_main.html
server/templates/users/users_signup.html

/pirogrmming_final_project/server/static/users/css/add_friend.css 에 검색창 참고!

[fix] 친구추가 로직 및 페이지 수정

---

server/apps/users/forms.py
server/apps/users/models.py
server/apps/users/views.py
server/static/users/css/signup.css
server/static/users/js/signup.js
server/templates/users/users_signup.html

다들 꼭 봐줘... 내 영혼을 갈아 넣었어....😢
한페이지 하는데... 4시간... 말이 되냐....ㅠ

[style] 회원가입 페이지 css

---

server/templates/users/users_signup.html

머지하다가 빠져버린거 같아서... 급하게 코드 한줄 추가욥!

[style] 다음 주소 api  script 빠진거 추가

---

server/apps/users/forms.py
server/apps/users/views.py
server/static/users/js/signup.js
server/static/users/js/update.js
server/templates/users/users_signup.html
server/templates/users/users_update.html

[style] 유저 정보 수정

---

server/apps/score/views.py
server/static/js/link.js
server/templates/communitys/posts/post_detail.html

[feat] 게시글 공유하기 작업 && 스코어 경로 수정,

---

server/apps/users/forms.py
server/apps/users/models.py
server/apps/users/views.py
server/config/settings.py
server/static/users/css/signup.css
server/static/users/js/update.js
server/templates/users/users_signup.html
server/templates/users/users_update.html

[style] js 일부 수정

---

requirements.txt
server/config/settings.py

.env 읽어올때 공백이 생겨버림... .strip()으로 해결

[fix] 네이버 로그인 에러 수정

---

server/apps/score/views.py
server/static/js/link.js

[fix] 머지 수정

---

server/static/users/css/signup.css
server/templates/users/users_signup.html

[style] 유저 회원가입 페이지 css

---

server/apps/users/views.py
server/static/users/css/user.css
server/templates/users/users_login.html

[style] 로그인 페이지 실패시 alert 추가

---

server/static/locations/javascript/myposition_script.js

지도에 나의 현재 위치랑 가장 가까운 5개 파크 골프장 나오게끔했음 -> 너무 오래걸려서 로딩 페이지 하나 만들게요ㅠ

[feat] 나의 위치와 주변 골프장 드디어 지도에 추가

---

server/static/users/css/friend_list.css
server/static/users/js/delete_friend.js
server/templates/users/friend_list.html
server/templates/users/users_login.html

[style] 유저의 친구목록 페이지 css

---

server/apps/search/views.py
server/apps/users/models.py
server/apps/users/views.py
server/static/search/js/search_friend.js
server/static/users/css/add_friend.css
server/static/users/js/add_friend.js
server/static/users/js/delete_friend.js
server/templates/users/add_friend.html
server/templates/users/friend_list.html

[style] 친구추가 시 email로 검색 추가

---

server/apps/users/views.py
server/static/users/js/update.js
server/templates/users/users_update.html

[feat] 회원가입 폼 나갈때 알림

---

server/static/posts/js/comment.js

[fix] 커뮤니티 댓글 수정시 원본 내용 있도록

---

server/static/board/css/board_list.css
server/static/posts/css/post_detail.css
server/static/posts/css/post_list.css
server/static/score/css/score_detail.css
server/static/users/css/user.css
server/templates/communitys/posts/post_list.html

사진 크기, 폰트 적용, overflow 같은 사소한 디테일 수정

[fix] 커뮤니티 디테일 수정

---

server/static/locations/css/location_detail.css
server/templates/locations/location_detail.html

수정하기 누르면 구글 폼 제출로 넘어가도록
기존 수정하기/삭제 버튼은 admin인 superuser 만 보이도록함
(python manage.py createsuperuser 으로 만든 계정만)

[style] 수정하기 및 추가한 데이터 css 수정

---

server/static/locations/javascript/location_review_filter.js

[fix] 리뷰 방식 변경시 정렬 안되는 문제 해결

---

server/static/locations/javascript/naver_blog.js
server/templates/locations/location_detail.html
server/templates/locations/location_list.html

[fix] 골프장 추가 admin 만 되도록

---

server/templates/users/users_update.html

[style] 회원가입 페이지 css 초큼 수정

---

server/static/main/css/style.css
server/static/score/css/score_create.css
server/static/score/css/score_detail.css

[feat] score 반응형

---

server/apps/communitys/models.py
server/apps/games/urls.py
server/apps/games/views.py
server/apps/search/urls.py
server/apps/search/views.py
server/static/games/css/search_users.css
server/static/games/js/search_users.js
server/templates/games/game_create.html
server/templates/games/game_popup.html

[feat] 플레이어 유저 검색 기능 추가

---

server/apps/users/models.py
server/config/settings.py

[db] s3 이미지 서버 올린거 반영

---

server/apps/users/forms.py
server/apps/users/models.py
server/apps/users/views.py
server/config/settings.py
server/templates/users/users_signup.html
server/templates/users/users_update.html

- 유저 view 안쓰는 코드 삭제
- 유저 모델 email null 허용

[fix] 유저 view 수정 및 모델 수정

---

server/apps/score/views.py

[fix] 스코어 스캔 폴더명 수정

---

server/apps/score/views.py
server/static/js/link.js
server/static/score/js/picture.js

[fix] 스코어 이미지 분석 업로드 경로 수정/ 인풋 없을 때 오류 수정

---

server/templates/users/users_main.html

[fix] 마이페이지 내 정보 수정

---

server/templates/locations/location_list.html

[fix] 현재 위치 버튼 수정

---

server/apps/locations/tests.py

[add] locations test case 추가

---

server/apps/communitys/tests.py
server/apps/communitys/tests/test_communitys.py
server/apps/search/urls.py
server/apps/search/views.py
server/config/settings.py
server/static/main/css/main.css
server/static/score/js/picture.js
server/static/search/js/search_main.js
server/static/search/js/search_main_result.js
server/templates/main.html
server/templates/search/search_main_result.html

[feat] 메인화면 검색 기능 추가, 전체 검색 페이지 작성중

---

server/apps/users/views.py
server/static/users/css/signup.css
server/templates/users/users_signup.html
server/templates/users/users_update.html

이러면 로그인/회원수정 페이지에서 생일 입력 받는 부분이 좀더 직관적으로 됨

[fix] user에서 birth 받는 input 태그 수정

---

README.md

리드미 업데이트 - 머지 부탁~

---

server/static/games/js/search_users.js
server/templates/games/game_create.html

[fix] 유저 검색시 검색버튼 누른 select이 바뀌도록 수정

---

server/static/locations/javascript/myposition_script.js

[add] 현재 위치 마커 정보 추가

---

server/static/locations/javascript/myposition_script.js

[fix] 마커 변수 오류 수정

---

server/static/locations/css/location_myposition.css
server/templates/locations/location_myplace.html

[fix] 현재 위치 css 수정

---

server/static/locations/javascript/location_review_filter.js
server/templates/score/score_create.html

[fix] 장소 선택 오류 수정

---

server/static/games/css/game_detail.css
server/static/users/css/friend_list.css

[fix] 반응형 수정
